"""with_images_url

Revision ID: 0dbb145e47fe
Revises: ebba129a73e2
Create Date: 2024-11-10 22:04:04.189753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dbb145e47fe'
down_revision: Union[str, None] = 'ebba129a73e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('Products', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('image_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Products', 'image_url')
    # ### end Alembic commands ###
