"""without_images

Revision ID: b5d00d06430f
Revises: 05e9a92e69a7
Create Date: 2024-11-10 21:23:10.088892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d00d06430f'
down_revision: Union[str, None] = '05e9a92e69a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Products', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('image_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
