"""with_images

Revision ID: ebba129a73e2
Revises: b5d00d06430f
Create Date: 2024-11-10 22:00:10.042396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebba129a73e2'
down_revision: Union[str, None] = 'b5d00d06430f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('image_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Products', 'image_id')
    # ### end Alembic commands ###
